### ISSUE TITLE
Tests create files in /tmp and ./

### ISSUE THREAD

**Issue by arpad-m** [domo-iot/libp2p-rust-dht#4]
There are a bunch of tests which is good, but they create files inside `/tmp`, and one test creates a file in the local directory (which I'll ignore for now to make the discussion simpler, it can be easily changed to use `/tmp`).

Storing test files in `/tmp` the way the code does is not good for multiple reasons: first, there is no cleanup after the tests finish. Second, `/tmp` is a shared resource and not unique per run, which means that running `cargo test` from multiple checkouts of this repository at the same time might lead to race conditions. Third, platforms like Windows do not have a `/tmp` directory.

To address the last point, one can use `std::env::temp_dir`, but it doesn't address the other two. To address all three points, one can use the [`tempdir`](https://docs.rs/tempdir/latest/tempdir/) crate as a dev-dependency, which creates a randomly named directory inside `/tmp` and then cleans it up, but it also introduces the need to keep around handles so that the tempdir crate doesn't clean up too early.

An alternative is to use the in-memory database support of sqlite. It would also need changes of the code in this repo, and would also address all three points. For the small amount of data the tests take, it shouldn't be a problem to use in-memory databases. 

Personally I'd prefer the last option.

**Comment by lu-zero** [comment]
If they are integration tests `CARGO_TARGET_TMPDIR` exists, see [here](https://doc.rust-lang.org/cargo/reference/environment-variables.html)

**Comment by arpad-m** [comment]
Yeah `CARGO_TARGET_TMPDIR` is also a good idea.

**Comment by arpad-m** [comment]
Done by https://github.com/sifis-home/libp2p-rust-dht/commit/db761c68cf3a4142b38a38362d60a1aa9337491f
